# Generated by Django 3.2.12 on 2022-06-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rig',
            name='config_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rig',
            name='pools',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rig',
            name='wallets',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
